"$schema" = "https://starship.rs/config-schema.json"
command_timeout = 200

format = """
$directory$git_branch$git_status$aws${custom.venv}$nodejs$bun$rust$deno$cmd_duration
$character"""

right_format = "$battery$time"

[battery]
format = "[$symbol$percentage]($style) "
charging_symbol = "[󰂄 ](#c3e88d)"

[[battery.display]]
threshold = 20
style = "bold #ff757f"

[[battery.display]]
threshold = 100
style = "#636da6"

[directory]
style = "bold #82aaff"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
symbol = ""
style = "#c099ff"
format = "[$symbol$branch]($style) "

[git_status]
style = "#ff757f"
format = "[$all_status$ahead_behind]($style) "

[aws]
format = "[$symbol($profile )($region)]($style) "
style = "#ffc777"
symbol = "\uf0c2 "

[custom.venv]
command = 'basename "$VIRTUAL_ENV"'
when = 'test -n "$VIRTUAL_ENV"'
format = "[$symbol$output]($style) "
symbol = "\ue606 "
style = "#c3e88d"
shell = ["sh"]

[nodejs]
symbol = "\ue718 "
style = "#636da6"
format = "[$symbol($version)]($style) "

[bun]
symbol = "\ue769 "
style = "#636da6"
format = "[$symbol($version)]($style) "

[rust]
symbol = "\ue7a8 "
style = "#636da6"
format = "[$symbol($version)]($style) "

[deno]
symbol = "🦕 "
style = "#636da6"
format = "[$symbol($version)]($style) "

[cmd_duration]
style = "#ffc777"
format = "[$duration]($style) "

[time]
disabled = false
style = "#636da6"
format = "[$time]($style)"
time_format = "%R"

[character]
success_symbol = "[❯](bold #86e1fc)"
error_symbol = "[❯](bold #ff757f)"

[python]
python_binary = ["python3", "python"]
detect_extensions = []
detect_files = []
